### ISSUE TITLE
Would it be possible to attach an MIT license to this?

### ISSUE THREAD

**Issue by mralexzee** [Didgeridooblastblock/LOD-Planets-in-Unity#1]
Based on Github's terms of service at https://choosealicense.com/no-permission, without a license, a repo owner retains all copyright rights. Is this intended or can we attach a license file - perhaps MIT license - that would allow for others to incorporate and expand on this within their own projects?

**Comment by HolmanDev** [comment]
Thank you for your comment! I've now added the MIT license to the repo.
